
# [START runtime]
service: adminstr
runtime: python27
threadsafe: yes

# [END runtime]

handlers:

  - url: /(.+)
    static_files: dist/wAdmin/\1
    upload: dist/wAdmin/(.*)

  - url: /
    static_files: dist/wAdmin/index.html
    upload: dist/wAdmin/index.html

# Temporary setting to keep gcloud from uploading not required files for deployment
skip_files:
  - ^node_modules$
#  - ^app\.yaml
  - ^README\..*
  - \.gitignore
  - ^\.git$
  - ^grunt\.js
  - ^src$
  - ^docs$
  - ^e2e$
  - \.editorconfig
  - ^karma\.config\.js
  - ^package\.json
  - ^protractor\.conf\.js
  - ^tslint\.json

